In [1]:
#import modules and libraries
import pandas as pd
from glob import glob

## Use glob() to list all files that match a pattern and sort results

In [2]:
stock_files = sorted(glob('data/UNSW-NB15_*.csv'))
stock_files

['data\\UNSW-NB15_1.csv',
 'data\\UNSW-NB15_2.csv',
 'data\\UNSW-NB15_3.csv',
 'data\\UNSW-NB15_4.csv']

### Build data frame from each csv file and store all data frames in one list

In [3]:
dataframes = []
for file in stock_files:
    dataframes.append(pd.read_csv(file))

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (1,3,47) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (3,39,47) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Getting column names from the featues file the assign it to each data frame in the list we created above

In [4]:
features = pd.read_csv("NUSW-NB15_features.csv", usecols=[1])
features_str = list(features.values.flatten())
for df in dataframes:
    df.columns = features_str

### Combining all dataframes into a big one

In [6]:
all_data = pd.concat(dataframes)

In [7]:
all_data['attack_cat'] = df['attack_cat'].fillna('Normal')
all_data.attack_cat.unique()

array(['Normal', 'Exploits', ' Fuzzers ', 'Backdoor', 'DoS', 'Generic',
       ' Reconnaissance ', ' Shellcode ', 'Analysis', 'Worms', nan],
      dtype=object)

### Get DoS attacks and Normal flows only from the all data

In [9]:
normal = all_data.loc[all_data['attack_cat'] == 'Normal'].sample(n=1000000)
dos = all_data.loc[all_data['attack_cat'] == 'DoS']
result = pd.concat([normal, dos])
result

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
128003,59.166.0.9,21855,149.171.126.6,25,tcp,FIN,0.496350,37428,3380,31,...,0,1,1,1,4,1,1,1,Normal,0
192059,59.166.0.4,22759,149.171.126.3,53,udp,CON,0.001000,146,178,31,...,,1,2,4,2,1,1,1,Normal,0
237025,59.166.0.6,11440,149.171.126.7,38633,tcp,FIN,0.020957,3390,41008,31,...,,5,4,2,6,1,1,1,Normal,0
394891,149.171.126.10,1043,175.45.176.0,53,udp,INT,0.000003,264,0,60,...,,31,31,12,12,12,12,31,Normal,0
120264,59.166.0.3,61200,149.171.126.7,53,udp,CON,0.000977,132,164,31,...,,1,2,2,3,1,1,2,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439257,175.45.176.2,28720,149.171.126.15,25,tcp,FIN,1.770885,2641,1802,62,...,,1,1,3,1,1,1,1,DoS,1
439344,175.45.176.3,46257,149.171.126.19,25,tcp,FIN,1.445151,86346,2292,62,...,,1,1,1,1,1,1,1,DoS,1
439944,175.45.176.0,18979,149.171.126.12,80,tcp,FIN,2.358193,330718,1816,62,...,,1,1,1,1,1,1,1,DoS,1
440025,175.45.176.0,33654,149.171.126.12,80,tcp,CON,2.579405,269883,1300,62,...,,2,1,2,4,2,2,2,DoS,1
440026,175.45.176.0,33654,149.171.126.12,80,tcp,CON,2.579405,269883,1300,62,...,,1,1,2,4,2,2,2,DoS,1

In [ ]:
result.to_excel("result.xlsx")